name: Documentation
description: Report an issue or enhancement related to https://scenic-lang.readthedocs.io/
labels:
  - "type: documentation"
  - "status: triage"

body:
  - type: markdown
    attributes:
      value: >
        #### Thank you for contributing! Before submitting a doc issue, please make sure it has no duplicate and has not already been addressed by searching through [the existing and past issues](https://github.com/BerkeleyLearnVerify/Scenic/issues)

  - type: textarea
    attributes:
      label: Describe the doc issue or enhancement
      description: >
        Please provide a clear and concise description of what content in https://scenic-lang.readthedocs.io/ has an issue or needs enhancement.
      placeholder: |
        Link to location in the docs: https://scenic-lang.readthedocs.io/
    validations:
      required: true

  - type: textarea
    attributes:
      label: Fix suggestion
      description: >
        Tell us how we could improve the documentation in this regard.

  - type: checkboxes
    attributes:
      label: Issue Submission Checklist
      options:
        - label: I am reporting an issue, not asking a question
          required: true
        - label: I checked the open issues, forum, etc. and have not found any solution
