name: format

on:
  push:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          persist-credentials: false

      - name: Run black to check formatting
        uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e
        with:
          version: "25.1.0"

      - name: Run isort to check import order
        uses: isort/isort-action@24d8a7a51d33ca7f36c3f23598dafa33f7071326
        with:
          isort-version: "5.12.0"
