name: run_coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref on which to run the tests.
        type: string
        required: true
  workflow_call:
    inputs:
      ref:
        description: Git ref on which to run the tests.
        type: string

jobs:
  coverage:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
        extras: ["test-full"]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout given ref
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      if: inputs.ref != ''
      with:
        ref: ${{ inputs.ref }}
        persist-credentials: false

    - name: Checkout current branch
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      if: inputs.ref == ''
      with:
        ref: ${{ github.ref }}
        persist-credentials: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Scenic and dependencies
      run: |
        python -m pip install -e ".[${{ matrix.extras }}]"

    - name: Run and report code coverage
      run: |
        pytest --cov --cov-report json

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: BerkeleyLearnVerify/Scenic
