name: Weekly CI tests

# Trigger every Thursday at 9:15 AM Pacific Time (16:15 UTC)
on:
  schedule:
    - cron: '15 16 * * 4'

permissions:
  contents: read

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      # Use the default branch" (i.e. main)
      ref: ''

  notify:
    name: Notify Slack
    needs: run-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
        - name: Post result to Slack
          uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52
          with:
            webhook: ${{ secrets.SLACK_WEBHOOK_URL}}
            webhook-type: incoming-webhook
            payload: |
              {
                "blocks": [
                    {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Weekly CI tests* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|run #${{ github.run_number }}> finished."
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${{ needs.run-tests.result == 'success' && '✅ All tests passed!' || '🚨 Some tests failed!' }}"
                    }
                  }
                ]
              }
